export const SET_REVIEW_OPTIONS = 'SET_REVIEW_OPTIONS';
export const INITIALIZE_FLASHCARDS = 'INITIALIZE_FLASHCARDS';
export const PUSH_TO_PROGRESS_HISTORY = 'PUSH_TO_PROGRESS_HISTORY';
export const CLEAR_PROGRESS_HISTORY = 'CLEAR_PROGRESS_HISTORY';
export const RESET_STATE = 'RESET_STATE';